apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reasonfm
spec:
  schedule: 0 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: app
              image: 'gcr.io/transcript-reason-town-fm/app:latest'
              args:
                - /bin/bash
                - ./run.sh
          restartPolicy: OnFailure
