apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reasonfm
spec:
  schedule: '*/1 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: 'gcr.io/transcript-reason-town-fm/app:latest'
              args:
                - /bin/sh
                - '-c'
                - 'date; echo "Hello, World!"'
          restartPolicy: OnFailure
