version: 2
references:
  master_br: &master_br
    only:
      - master
  build_env: &build_env
    machine: true
  prepare: &prepare
    run:
      name: Setup global dependencies
      command: |
        sudo apt-get update
        docker --version
        echo $GOOGLE_CLOUD_PLATFORM_API_KEY > secret.json

        git config --global user.name "kogai"
        git config --global user.email "$EMAIL"
        
  do_job: &do_job
    run:
      name: Generate new episode
      command: |
        rm -f audio/*.flac
        rm -f audio/*.mp3 
        docker build -t reasonfm .
        docker run --rm -v `pwd`/audio:/app/audio -t reasonfm 
        bash .circleci/commit.sh

jobs:
  do_job:
    <<: *build_env
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "7b:67:b5:f5:bb:a6:e2:ff:52:f3:8e:1e:ac:f4:29:07"
      - *prepare
      - *do_job

workflows:
  version: 2
  scheduled:
    triggers:
      - schedule:
          cron: "0,10 0,14 * * *"
          filters:
            branches: *master_br
    jobs:
      - do_job
